//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDtoON.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DND Notebook")]
        public string Notebook {
            get {
                return ((string)(this["Notebook"]));
            }
            set {
                this["Notebook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Races")]
        public string OneNoteSection {
            get {
                return ((string)(this["OneNoteSection"]));
            }
            set {
                this["OneNoteSection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("race")]
        public string BlockType {
            get {
                return ((string)(this["BlockType"]));
            }
            set {
                this["BlockType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Storm King\'s Thunder Bestiary 1.1.0.xml")]
        public string BestiaryFile {
            get {
                return ((string)(this["BestiaryFile"]));
            }
            set {
                this["BestiaryFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monster Block (Normal)")]
        public string MonsterBlockTemplate {
            get {
                return ((string)(this["MonsterBlockTemplate"]));
            }
            set {
                this["MonsterBlockTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PHB Spells 3.9.0.xml")]
        public string SpellsFile {
            get {
                return ((string)(this["SpellsFile"]));
            }
            set {
                this["SpellsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spell Block (Normal)")]
        public string SpellBlockTemplate {
            get {
                return ((string)(this["SpellBlockTemplate"]));
            }
            set {
                this["SpellBlockTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orc.xml")]
        public string RacesFile {
            get {
                return ((string)(this["RacesFile"]));
            }
            set {
                this["RacesFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Race Block (Normal)")]
        public string RaceBlockTemplate {
            get {
                return ((string)(this["RaceBlockTemplate"]));
            }
            set {
                this["RaceBlockTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UA Feats.xml")]
        public string FeatsFile {
            get {
                return ((string)(this["FeatsFile"]));
            }
            set {
                this["FeatsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feat Block (Normal)")]
        public string FeatBlockTemplate {
            get {
                return ((string)(this["FeatBlockTemplate"]));
            }
            set {
                this["FeatBlockTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Backgrounds.xml")]
        public string BackgroundsFile {
            get {
                return ((string)(this["BackgroundsFile"]));
            }
            set {
                this["BackgroundsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Background Block (Normal)")]
        public string BackgroundBlockTemplate {
            get {
                return ((string)(this["BackgroundBlockTemplate"]));
            }
            set {
                this["BackgroundBlockTemplate"] = value;
            }
        }
    }
}
